services:
  postgres:
    image: postgres:16
    container_name: transaction-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: transaction-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
